# week04/example-2/k8s/frontend.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: week04_example02_frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-w04e2 # Service name matches
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # The port the service listens on inside the cluster
      targetPort: 80 # The port on the Pod (containerPort where Nginx runs)
      nodePort: 30002 # A high port (30000-32767) on your host machine to access the service (distinct from others)
  type: NodePort # Exposes the service on a port on each Node's IP
