version: '3.9'

services:
  product_service:
    build: ./backend/product_service
    container_name: product_service
    ports:
      - "8000:8000"
    env_file:
      - ./backend/product_service/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: 5432

  order_service:
    build: ./backend/order_service
    container_name: order_service
    ports:
      - "8001:8001"
    env_file:
      - ./backend/order_service/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: 5432

  # React Frontend
  react_app:
    build:
      context: ./frontend/react-app
      dockerfile: Dockerfile
    container_name: react_app_container
    env_file:
      - ./frontend/react-app/.env
    ports:
      - "3000:3000"
    depends_on:
      - product_service
      - order_service
