# week04/example-3/k8s/order-service.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-w04e3
  namespace: ecomm-w04e3-local-k8s
  labels:
    app: order-service
spec:
  replicas: 1 # Defaulting to 1 replica
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service-container
        image: week04_example03_order_service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
        env:
        # Database connection details
        - name: POSTGRES_HOST
          value: order-db-service-w04e3 # Connects to the internal K8s Service for Order DB
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w04e3
              key: ORDERS_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w04e3
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w04e3
              key: POSTGRES_PASSWORD
        
        # RabbitMQ connection for publishing order events
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w04e3
              key: RABBITMQ_HOST
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w04e3
              key: RABBITMQ_USER
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w04e3
              key: RABBITMQ_PASS
        - name: CUSTOMER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w04e3
              key: CUSTOMER_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-w04e3 # Service name matches
  namespace: ecomm-w04e3-local-k8s
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8001 # The port the service listens on inside the cluster
      targetPort: 8000 # The port on the Pod (containerPort)
      nodePort: 30001 # A high port (30000-32767) on your host machine to access the service (distinct from product-service)
  type: NodePort # Exposes the service on a port on each Node's IP
