# week05/example-1/k8s/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: ecomm-secrets-w05-aks
  namespace: ecomm-w05-aks # Namespace name matches
type: Opaque # Indicates arbitrary user-defined data
data:
  # PostgreSQL Credentials (for all three DBs)
  POSTGRES_USER: "cG9zdGdyZXM=" # Base64 for 'postgres'
  POSTGRES_PASSWORD: "cG9zdGdyZXM=" # Base64 for 'postgres'

  # RabbitMQ Credentials
  RABBITMQ_USER: "Z3Vlc3Q=" # Base64 for 'guest'
  RABBITMQ_PASS: "Z3Vlc3Q=" # Base64 for 'guest'

  # Azure Storage Account Credentials for Product Service image uploads (from Week 03 Example 3)
  # REPLACE WITH YOUR ACTUAL BASE64 ENCODED VALUES
  # Example: echo -n 'myazurestorageaccount' | base64
  AZURE_STORAGE_ACCOUNT_NAME: ""
  # Example: echo -n 'your_storage_account_key_string' | base64
  AZURE_STORAGE_ACCOUNT_KEY: ""