version: '3.9'

services:
  product_service:
    build: ./backend/product_service
    container_name: product_service
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: 5432

  react_app:
    build:
      context: ./frontend/react-app
      dockerfile: Dockerfile
    container_name: react_app_container
    ports:
      - "3000:3000"
    depends_on:
      - product_service
    stdin_open: true
    tty: true
