version: "3.9"
services:
  db:
    image: postgres:14
    container_name: product_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  product_service:
    build: ./backend/product_service
    container_name: product_service_container
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  react_app:
    build:
      context: ./frontend/react-app
      dockerfile: Dockerfile
    container_name: react_app_container
    ports:
      - "3000:3000"
    depends_on:
      - product_service
    stdin_open: true
    tty: true