name: Week 7 Python CI

on:
  pull_request:
    paths:
      - "python/week07/**"
  push:
    branches:
      - main
    paths:
      - "python/week07/**"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
        with:
          path: python/week07

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/week07/backend/requirements.txt
          pip install isort flake8 pytest

      - name: Check import order with isort
        run: |
          isort --check-only python/week07/backend

      - name: Lint with flake8
        run: |
          flake8 python/week07/backend

      - name: Run pytest
        run: |
          pytest python/week07/backend --maxfail=1 --disable-warnings -q
